;ФАЙЛ lr05-4-1.asm
PUBLIC X
EXTRN CHANGE: far

SSTK SEGMENT para STACK 'STACK'
    DB 100 dup(0)
SSTK ENDS

SD1 SEGMENT PARA PUBLIC 'DATA'
    X DB 'X'
SD1 ENDS

SC1 SEGMENT PARA PUBLIC 'CODE'
    ASSUME CS:SC1, DS:SD1, SS: SSTK
    MAIN:
        MOV AX,SD1
        MOV DS,AX
        JMP CHANGE
SC1 ENDS
END MAIN